name: timming_matters
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Firebase
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.15.3

  # UI & Animations
  glassmorphism: ^3.0.0
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # Navigation
  go_router: ^12.1.3

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9

  # Notifications
  # awesome_notifications: ^0.8.2

  # Charts & Data Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.1.41

  # Utils
  uuid: ^4.2.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Icons & Fonts
  iconsax: ^0.0.8
  google_fonts: ^6.1.0

  # Cupertino Icons
  cupertino_icons: ^1.0.8
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints & Code Generation
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

# Flutter-specific options
flutter:
  uses-material-design: true

  # Assets (uncomment jika dibutuhkan)
  # assets:
  # #   - assets/

  # # Fonts (contoh)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic